# Stage 1: Build environment
FROM node:18.18.1-alpine

# Set the working directory for the application
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Update and upgrade packages, then install necessary dependencies
RUN apk update && \
    apk upgrade

# Stage 2: Node environment

# Install necessary packages including ca-certificates, bash, and PostgreSQL client
RUN apk --no-cache add bash postgresql-client

# Install Node.js dependencies without executing scripts
RUN npm ci --ignore-scripts

# Copy necessary files and directories for database migrations
COPY ./db ./db/
COPY .db-migraterc .db-migraterc
COPY ./db/migrations/scripts/migration_entrypoint.sh ./

# Check whether the database exists
CMD ["/bin/bash", "/migration_entrypoint.sh"]

# Run DB migrations 
CMD [ "npm", "run", "migrate:up" ]
